### ISSUE TITLE
Clarification of text in Riot Guide: Loops?

### ISSUE THREAD

**Issue by jmk2142** [riot/riot.github.io#228] opened 2018-06-19 23:57 UTC
1. Describe your issue:

Documentation description seems inaccurate
https://riot.js.org/guide/#loops
> `this.items = [ { title: 'First' }, { title: 'Second' } ]`
> `<todo-item each="{ items }" data="{ this }"></todo-item>`
> The currently looped item can be referenced with this which you can use to pass the item as an option to the looped tag.

"Currently looped item" would seem to indicate that each item object in the list would be found in the `todo-item` child tag options. E.g. `tagA.opts.data = {title:'First'}`, `tagB.opts.data = {title:'Second'}`... etc.

But instead, doing as described above seems to give: `tagA.opts.data.items = [ { title: 'First' }, { title: 'Second' } ]` Which is basically where `this` represented the tag being passed in, not the "Currently looped item."

So I guess I'm wondering what the point is that is trying to be made here.

If I want easy reference to the original list, I would just do something like:
`<todo-item each="{ items }" data="{ items }"></todo-item>`
So that my options would look like `tagA.opts.data = [...]`

I can get the item object through something like an event using `event.item`.

If the specific item is supposed to be easy to access, shouldn't the guide demo code end up like this?
`this.items = [ { title: 'First' }, { title: 'Second' } ]`
`<todo-item each="{ items }" data="{ this }"></todo-item>`
`tagA.opts.data = {title:'First'}`, `tagB.opts.data = {title:'Second'}`

If this is a documentation error, easy fix. But if the intent is easy access to the item in the list being looped through - via passing `this` as an opt - not sure if this is a bug.

2. Can you reproduce the issue?
  - https://codepen.io/jmk2142/pen/QxQgbX?editors=1011

3. On which browser/OS does the issue appear?
  - OSX, Chrome

4. Which version of Riot does it affect?
  3.10.2

5. How would you tag this issue?

  - [X] Question
  - [?] Bug

**Comment by GianlucaGuarini** [comment] 2018-12-13 07:56
I have transferred this issue because it's not a bug but just a documentation update request. Any PR is welcome

**Comment by GianlucaGuarini** [comment] 2019-06-05 20:11
closing this issue due to inactivity. I hope Riot.js@4 loops are much clearer now

**Closed by GianlucaGuarini** 2019-06-05 20:11 UTC
Labels: enhancement, good for beginner
